apiVersion: v1
kind: PersistentVolume
metadata:
  name: cephfs-pv
  labels:
    pv: cephfs-pv
spec:
  capacity:
    storage: 120Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 192.168.222.219:6789
      - 192.168.222.220:6789
      - 192.168.222.221:6789
    user: admin
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Delete
