apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx   #Controllrt控制器的名字
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx  #匹配名为nginx的Pod
  template:
    metadata:
      labels:
        app: nginx    #Pod的标签
    spec:
      containers:
      - name: n1
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
