apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: n1
        image: nginx:latest
        imagePullPolicy: IfNotPullPresent
        ports:
        - name: http
          contianerPort: 80
          