apiVersion: v1
kind: Service
metadata:
  name: headless1
  namespace: default
spec:
  type: ClusterIP          #ClusterIP类型，也是默认的类型
  clusterIP: None          #None就是代表无头Service
  ports:
  - port: 80            #Service端口
    protocol: TCP       #端口协议
    targetPort: 80      #Pod的端口
  selector:
    app: nginx          #关联后端Pod的标签