apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb
spec:
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
      - name: n1-lb
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  ports:
  - type: LoadBalancer
    port: 8090
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-lb
    