apiVersion: apps/v1
kind: Deployment
metadata:
  name: np1
  labels:
    app: np1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-np1          #关联Pod的标签
  template:
    metadata:
      labels:
        app: nginx-np1   #Pod标签
    spec:
      containers:
      - name: n1
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: np1
  namespace: default
spec:
  type: NodePort
  selector: 
    app: nginx-np1     #关联Pod的标签
  ports:
  - port: 80
    protocol: TCP
    nodePort: 31111
    targetPort: 80