apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob1
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nginx-job1
            image: nginx:latest
            imagePullPolicy: IfNotPresent
            command: ["/bin/sh", "-c", "echo $(date) >> /usr/share/nginx/html/index.html"]
            ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  createTimestamp: null
  name: job1
  labels:
    app: job1
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cronjob1
  type: NodePort