apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob2
spec:
  schudule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: docker.io/radial/busyboxplus
            imagePullPolicy: IfNotPresent
            args:
            - /bin/sh
            - -c
            - date; echo kubernetes txt
          restartPolicy: OnFailure