#svc
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: halo1
  labels:
    app: halo1
spec: 
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: halo-web
  type: NodePort
---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: halo-dm
  labels:
    app: halo-dm
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: halo-web
  template:
    metadata:
      labels:
        app: halo-web
    spec:
      containers:
      - name: halo-web
        image: linjiangyu/halo:v2
        imagePullPolicy: Never
        ports:
        - name: web-http
          containerPort: 8090  
        livenessProbe: 
          tcpSocket:
            port: 8090
          initialDelaySeconds: 3
          periodSeconds: 5
#      restartPolicy: OnFailure    此处测试错误，因为Deployment Controllrt 控制器有自己的重启策略