apiVersion: batch/v1
kind: Job
metadata:
  name: job1   #job名
spec:
  template:
    metadata:
      name: job1    #Pod名
    spec:
      containers:
      - name: pi         #容器名
        image: perl:latest
        imagePullPolicy: IfNotPresent
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never  #执行完不再重启