#mysqldump work namenode:node2 Job
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-dump
spec:
  template:
    metadata:
      name: mysql-dump
    spec:
      nodeName: node2
      containers:
      - name: mysql-dump
        image: mysql:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "mysqldump --host=mysqldump-svc-job -uroot -pabcd0702 --databases mysql > /root/mysql-k8s.sql"]
        volumeMounts:
        - mountPath: /root
          name: mysql-data
      restartPolicy: Never
      volumes:
      - name: mysql-data
        hostPath:
          path: /data  