#Error to mysql connect host no found 
#svc,StatefulSet
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldump-svc-job
  namespace: default
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql-state
---
#mysql-state  StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysqldb
  namespace: default
spec:
  selector:
    matchLabels:
      app: mysql-state
  serviceName: mysqldump-svc-job
  template:
    metadata:
      labels:
        app: mysql-state
    spec:
      nodeName: node3
      containers:
      - name: mysql
        image: mysql:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'abcd0702'
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-data
      volumes:
      - name: mysql-data
        hostPath:
          path: /data
