---
apiVersion: v1
kind: Namespace
metadata: 
  name: mem
---
apiVersion: v1
kind: Pod
metadata: 
  name: podmem
  namespace: mem
spec: 
  containers: 
  - name: stress
    image: docker.io/progrium/stress
    imagePullPolicy: IfNotPresent
    resources: 
      requests: 
        memory: "100Mi"
      limits: 
        memory: "200Mi"
    command: [ "stress" ]
            # 1核，150M和最少一个进程符合限制，启动会正常
    args: [ "--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1" ]
