apiVersion: v1
kind: Pod
metadata: 
  name: liveness-pod1
spec: 
  containers: 
  - name: liveness-1
    image: docker.io/busybox
    imagePullPolicy: IfNotPresent
    args: 
    - /bin/sh
    - -c
    - touch /tmp/test; sleep 60; rm -f /tmp/test; sleep 600
    livenessProbe:
      exec: 
        command: 
        - cat
        - /tmp/test
      initalDelaySeconds: 5     #在Pod启动后延迟5秒探测
      periodSeconds: 5          #每5秒探测一次