#livenessProbe+readinessProbe
apiVersion: v1
kind: Pod
metadata: 
  name: nginx-lr1
  namespace: default
  labels: 
    app: nginx-lr
spec: 
  containers:
  - name: nginx-lr
    image: nginx:1.14
    imagePullPolicy: IfNotPresent
    ports: 
    - name: http
      containerPort: 80
    livenessProbe:
      httpGet: 
        port: http
        path: /index.html
      initialDelaySeconds: 1
      periodSeconds: 3
    readinessProbe: 
      httpGet:
        port: http
        path: /index.html
      initialDelaySeconds: 10
      periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: live-read
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector: 
    app: nginx-lr
---
#这样可以保证存活和业务的可用性
