apiVersion: v1
kind: Pod
metadata: 
  name: livenes2
spec: 
  containers: 
  - name: nginx-liveness
    image: nginx:1.14
    imagePullPolicy: IfNotPresent
    ports: 
    - name: http
      containerPort: 80
    livenessProbe: 
      tcpSocket:        #tcpSocket
        port: 80        #连接80端口进行探测
      initialDelaySeconds: 5
      periodSeconds: 5
