#这个namespace已经在上一个能通过资源限制的yaml文件创建了,所以注释掉
#---
#apiVersion: v1
#kind: Namespace
#metadata: 
#  name: mem
#---
apiVersion: v1
kind: Pod
metadata: 
  name: stress-max
  namespace: mem
spec: 
  containers: 
  - name: stress
    image: docker.io/progrium/stress
    imagePullPolicy: IfNotPresent
    resources: 
      requests:
        memory: "100Mi"
      limits: 
        memory: "200Mi"
    command: [ "stress" ]
           #1核，210M内存，最少一个进程,210M进程不符合limits限制，运行后pod会被杀死，
           #STATUS显示OOMKilled然后是CrashLoopBackOff，describe显示Back-off restarting failed container
    args: [ "--vm","1","--vm-bytes","210M","--vm-hang","1" ]
