apiVersion: v1
kind: Pod
metadata:
  name: nginx-vo1
  namespace: default
  labels:
    app: nginx-vo1
spec:
  containers:
  - name: nginx-vo1
    image: nginx:latest
    imgaePullPolicy: IfNotPresent
    ports:
    - name: http-nginx
      containerPort: 80
    volumeMounts:
    - name: html-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html-data
    hostPath:
      path: /opt/html