#这里已经把想要的指定节点打上了app=webserver标签
#kubectl label nodes node2 app=webserver
apiVersion: v1
kind: Pod
metadata: 
  name: nodeselector1
  namespace: default
spec:
  nodeSelector:
    app: webserver
  containers:
  - name: nginx-ns
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - name: http
      containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dd
  name: dd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nodeselector1
  type: NodePort