---
apiVersion: v1 
kind: Namespace
metadata: 
  name: pod-default
---
apiVersion: v1
kind: Pod
metadata: 
  name: pod1
  namespace: pod-default
spec: 
  containers: 
  - name: pod1
    image: docker.io/progrium/stress
    imagePullPolicy: IfNotPresent

  - name: pod2
    image: docker.io/progrium/stress
    imagePullPolicy: IfNotPresent
