apiVersion: v1
kind: Pod
metadata: 
  name: poststart1
  namespace: default
spec:
  containers: 
  - name: nginx-ps
    image: nginx:1.14
    imagePullPolicy: IfNotPresent
    lifecycle: 
      postStart: 
        exec: 
          command: ["/bin/sh","-c","sleep 30","echo 'test postStart' > /usr/share/nginx/html/index.html"]