---
apiVersion: v1
kind: Pod
metadata: 
  name: readiness1
  namespace: default
  labels:
    app: readiness1
spec: 
  containers: 
  - name: nginx-readiness1
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    ports: 
    - name: http
      containerPort: 80
    readinessProbe:
      httpGet:
        port: http
        path: /index.html
      initialDelaySeconds: 3
      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata: 
  name: readiness-1
spec: 
  type: ClusterIP
  ports: 
  - port: 80
    targetPort: 80
  selector: 
    app: readiness1