--- #定义PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv1
spec:
  accessModes:    #读写权限
    - ReadWriteMany
  capacity:
    storage: 10Gi  #可用空间
  nfs:
    path: /nfs     #nfs的共享路径
    server: node4  #nfs服务器地址
--- #定义PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---  #定义SVC
apiVersion: v1
kind: Service
metadata:
  name: pv1        #SVC名字
spec:
  type: NodePort
  selector:
    app: pv2     #关联的Pod
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pv1        #Deployment控制器名字
  labels:
    app: nginx-pv1     
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pv2           #关联的Pod
  template:
    metadata:
      labels:
        app: pv2         #Pod名字
    spec:
      containers:
      - name: nginx-pv-nfs   #容器名字
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: nginx-http   #端口名字
          containerPort: 80
        volumeMounts:
        - name: nginx-pv       #使用的存储卷
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-pv          #创建的卷名
        persistentVolumeClaim:
          claimName: nginx-pvc1 #使用的PVC