version: '1'
services: 
  php-fpm: 
    image: php:latest
    tty: true
    networks: 
      - lnmp
    expose: 
      - "9000"
    links: 
      - mysql

  mysql: 
    image: mysql:latest
    restart: always
    networks: 
      - lnmp
    volumes: 
    - "./data:/var/lib/mysql" 
    environment: 
      MYSQL_ROOT_PASSWORD: abcd0702
      MYSQL_DATABASE: tp5shop
      MYSQL_USER: tp5shop
      MYSQL_PASSWORD: abcd0702
    expose:
      - "3306"
  nginx:
    image: nginx:latest
    restart: always
    networks:
      - lnmp
    ports: 
      - "80:80"
    links: 
      - mysql
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./html/:/usr/share/nginx/html/"
networks: 
  lnmp:
