#创建Namespace
---
apiVersion: v1
kind: Namespace
metadata: 
  name: mem
---
apiVersion: v1
kind: Pod
metadata: 
  name: pod2-stree
  namespace: mem
spec: 
  containers: 
  - name: stress1-pod2
    image: docker.io/progrium/stress
    imagePullPolicy: IfNotPresent
    resources: 
      requests:
        memory: "100Mi"
      limits: 
        memory: "200Mi"
    command: [ "stress" ]
    args: [ "--vm","1","--vm-byte","190M","--vm-hang","1" ]
  - name: stress2-pod2
    image: docker.io/progrium/stress
    imagePullPolicy: IfNotPresent
    resources: 
      requests:
        memory: "100Mi"
      limits: 
        memory: "200Mi"
    command: [ "stress" ]
    args: [ "--vm","1","--vm-byte","210M","--vm-hang","1" ]